# Generated by Django 5.1 on 2024-09-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtlogin', '0003_alter_myuser_options_alter_myuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
            ],
        ),
    ]
